function createfigure(X1, YMatrix1, ZMatrix1)
%CREATEFIGURE(X1, YMATRIX1, ZMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  ZMATRIX1:  matrix of z data

%  Auto-generated by MATLAB on 15-May-2015 10:10:31

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Visible','off','Parent',figure1,...
    'PlotBoxAspectRatio',[0.5 1.25 0.2],...
    'DataAspectRatio',[3000 20 5],...
    'CameraViewAngle',5.18033628450948,...
    'CameraTarget',[2872.34608898191 17.4749269741339 1],...
    'CameraPosition',[18931.2121486026 -206.97915866528 28.6797658886463]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[1000 4000]);
%% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[0 2]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot3
plot3(X1,YMatrix1,ZMatrix1,'Parent',axes1);

