function [ h ] = plot_spectsum(X1, Y1, kmin, kmax, xlab, ylab)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 15-May-2015 09:22:19

plot_num = min(size(Y1));

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontSize',12,...
    'FontName','MyriadPro-Regular');
%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[kmin kmax]);
box(axes1,'on');
hold(axes1,'on');

% Create ylabel
ylabel(ylab);

% Create xlabel
xlabel(xlab);

% Create multiple lines using matrix input to plot
plot1 = plot(X1,Y1,'LineWidth',1,'Parent',axes1);
set(plot1(plot_num),'LineWidth',2,'Color',[0 0 0]);

